"""empty message

Revision ID: 419696890e84
Revises: 45cbba448346
Create Date: 2025-01-07 17:30:19.611161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419696890e84'
down_revision = '45cbba448346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendly_name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friendly_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('friendly_name')

    with op.batch_alter_table('permission_types', schema=None) as batch_op:
        batch_op.drop_column('friendly_name')

    # ### end Alembic commands ###
