"""empty message

Revision ID: ff55c408ed1e
Revises: 1493f878f07c
Create Date: 2025-03-31 21:44:07.484115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff55c408ed1e'
down_revision = '1493f878f07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_services',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'service_id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nonprod_pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prod_pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sc_clearance', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'pids', ['nonprod_pid'], ['uid'])
        batch_op.create_foreign_key(None, 'pids', ['prod_pid'], ['uid'])
        batch_op.drop_column('pid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sc_clearance')
        batch_op.drop_column('prod_pid')
        batch_op.drop_column('nonprod_pid')

    op.drop_table('request_services')
    # ### end Alembic commands ###
