def register_routes(app):
    from accessflow.views.index import IndexView
    from accessflow.views.requests.list import RequestListView
    from accessflow.views.requests.create import RequestCreateView
    from accessflow.views.admin.dashboard import AdminIndexView
    from accessflow.views.admin.requests.list import AdminRequestListView
    from accessflow.views.admin.pids.list import AdminPIDListView
    from accessflow.views.admin.teams.list import AdminTeamListView
    from accessflow.views.admin.services.list import AdminServiceListView
    from accessflow.views.admin.services.create import AdminServiceCreateView
    from accessflow.views.admin.services.delete import AdminServiceDeleteView
    from accessflow.views.admin.users.list import AdminUserListView
    from accessflow.views.admin.users.create import AdminUserCreateView
    from accessflow.views.admin.users.delete import AdminUserDeleteView
    from accessflow.views.admin.jobs.list import AdminJobListView
    from accessflow.views.admin.jobs.logs import AdminJobLogsView
    from accessflow.views.admin.jobs.run import AdminJobRunView
    from accessflow.views.admin.logs.list import AdminLogsListView
    from accessflow.views.admin.authentication.login import AdminLoginView
    from accessflow.views.admin.authentication.login_two_factor import AdminLoginTwoFactorView
    from accessflow.views.admin.authentication.logout import AdminLogoutView

    app.add_url_rule("/", view_func = IndexView.as_view("index"))
    app.add_url_rule("/requests", view_func = RequestListView.as_view("requests"))
    app.add_url_rule("/requests/create", view_func = RequestCreateView.as_view("requests/create"))
    app.add_url_rule("/admin", view_func = AdminIndexView.as_view("admin/index"))
    app.add_url_rule("/admin/requests", view_func = AdminRequestListView.as_view("admin/requests"))
    app.add_url_rule("/admin/pids", view_func = AdminPIDListView.as_view("admin/pids"))
    app.add_url_rule("/admin/teams", view_func = AdminTeamListView.as_view("admin/teams"))
    app.add_url_rule("/admin/services", view_func = AdminServiceListView.as_view("admin/services"))
    app.add_url_rule("/admin/services/create", view_func = AdminServiceCreateView.as_view("admin/services/create"))
    app.add_url_rule("/admin/services/delete", view_func = AdminServiceDeleteView.as_view("admin/services/delete"))
    app.add_url_rule("/admin/users", view_func = AdminUserListView.as_view("admin/users"))
    app.add_url_rule("/admin/users/create", view_func = AdminUserCreateView.as_view("admin/users/create"))
    app.add_url_rule("/admin/users/delete", view_func = AdminUserDeleteView.as_view("admin/users/delete"))
    app.add_url_rule("/admin/jobs", view_func = AdminJobListView.as_view("admin/jobs"))
    app.add_url_rule("/admin/jobs/logs", view_func = AdminJobLogsView.as_view("admin/jobs/logs"))
    app.add_url_rule("/admin/jobs/run", view_func = AdminJobRunView.as_view("admin/jobs/run"))
    app.add_url_rule("/admin/logs", view_func = AdminLogsListView.as_view("admin/logs"))
    app.add_url_rule("/admin/login", view_func = AdminLoginView.as_view("admin/login"))
    app.add_url_rule("/admin/login/two-factor", view_func = AdminLoginTwoFactorView.as_view("admin/login/two-factor"))
    app.add_url_rule("/admin/logout", view_func = AdminLogoutView.as_view("admin/logout"))